spring.application.name=Findacountrybasedoncountrycode
spring.application.name=orm-learn

# -----------------------------
# Database Configuration
# -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=Mamidala@5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -----------------------------
# Hibernate Configuration
# -----------------------------
spring.jpa.hibernate.ddl-auto=validate

# Optional: Hibernate automatically detects the dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# -----------------------------
# JPA / Hibernate SQL Logging
# -----------------------------
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -----------------------------
# Logging Configuration
# -----------------------------
logging.level.org.springframework=INFO
logging.level.com.cognizant=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.pattern.console=%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-35.35logger{35} %m%n